//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3dSessionMonitorWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class instance
    {
        public instance()
        {
            this.locations = new HashSet<location>();
            this.sessiondatas = new HashSet<sessiondata>();
        }
    
        public int id { get; set; }
        public string externalId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime creationTimeStamp { get; set; }
    
        public virtual ICollection<location> locations { get; set; }
        public virtual ICollection<sessiondata> sessiondatas { get; set; }
    }
}
