//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3dSessionMonitorWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class messagelog
    {
        public int id { get; set; }
        public string externalID { get; set; }
        public System.DateTime timestamp { get; set; }
        public string dataType { get; set; }
        public string data { get; set; }
    }
}
