//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3dSessionMonitorWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public session()
        {
            this.sessiondatas = new HashSet<sessiondata>();
        }
    
        public int id { get; set; }
        public int setupId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<sessiondata> sessiondatas { get; set; }
        public virtual setup setup { get; set; }
    }
}
