//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3dSessionMonitorWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class setup
    {
        public setup()
        {
            this.locations = new HashSet<location>();
            this.sessions = new HashSet<session>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime creationTimestamp { get; set; }
    
        public virtual ICollection<location> locations { get; set; }
        public virtual ICollection<session> sessions { get; set; }
    }
}
